spring:
  application:
    name: usian-sso-web
  rabbitmq:
    host: 192.168.25.129
    username: zongyiwu
    password: 123
    virtual-host: /usian  
server:
  port: 8098
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
